### ISSUE TITLE
DRM каналы

### ISSUE THREAD

**Issue by Silergo** [sybdata/ace86a37#1]
Можно в контейнер как-то встроить httpLiveKeyLoader (с соответствующей дллкой) для расшифровки каналов?

**Comment by sybdata** [comment]
дайте больше инфы по "httpLiveKeyLoader", посмотрим что можно будет сделать

**Comment by Silergo** [comment]
Без проблем. Есть такой плеер SimpleTV (https://simple-tv.torrent-telik.com/download_pro.html) Для расшифровки некоторых плейлистов (точнее одного известного плейлиста на букву z), а еще точнее для расшифровки каналов, он использует httpLiveKeyLoader в папке \luaScr\user\httpLiveKeyLoader. Вот сама папка если нужна: https://yadi.sk/d/E4_4iqRErJ0Qyw 
Может ли, например, прокси брать поток, расшифровывать и выдавать чистый в сеть как делает этот плеер?

**Comment by sybdata** [comment]
плейлист забавы состоит из http потоков
эта же прокси заточена на р2р потоки

попробуйте через астру прогнать

**Comment by Silergo** [comment]
Астра может расшифровывать ДРМ?

**Comment by sybdata** [comment]
у меня здесь [где-то валяется сборка](https://github.com/sybdata/ace86a37/tree/astra) для астры которую попросили специально для забавы
и говорят что идут каналы
сам не разбирался что там с дрм

**Comment by Silergo** [comment]
docker: Error response from daemon: Bind mount failed: '/etc/astra/astra.conf' does not exists.

**Comment by sybdata** [comment]
> Как добавить каналы?

[sample-astra.conf](https://raw.githubusercontent.com/sybdata/ace86a37/astra/sample-astra.conf)

**Comment by Silergo** [comment]
Да, спасибо.
Только по адресу http://172.19.0.5:8100/keys/s/ace/566950204d656761686974204844/hls/v3/i.m3u8 канала не может быть
Если добавить канал З (например, http://zabava-htlive.cdn.ngenix.net/hls/CH_C03_PARAMOUNTCOMEDYHD/variant.m3u8), то получется 0 kBit/s и в логе вот это:
[Astra Log.txt](https://github.com/sybdata/ace86a37/files/3493882/Astra.Log.txt)

**Comment by sybdata** [comment]
Вопрос не по адресу . Я без понятия и не занимаюсь расшифровкой ДРМ.
